apps/end-tenancy/controllers/address-lookup.js
As fields are dynamically added this needs to be done before attempting to append values to options. This is due to multi-instance
=> bugfix - set fields before attempting to append options

apps/end-tenancy/controllers/loop.js
Currently when clicking edit tenant date left, the page is redirected to the start of the tenant loop so there is no easy way to amend just one piece of information
* check if req.params.edit is truthy before redirection logic
=> Bugfix LCS-145  - editing a tenant from confirm page

.gitignore, package.json
Some reasons for this
1. There have been some improvements to hof-template-mixins, e.g. making the year field bigger.  I wanted to capture this to resolve an old bug in end-tenancy
2. I'm going to pick up a story for end-tenancy so I thought it would be a good idea to update hof before I do.
=> Upgrade to hof v12.1.1 & hof-theme-govuk 2.0.4

package.json
- Because 1.3.3 is old
- there are a lot of useful features in the latest version e.g. watching markdown, having a separate .env file
=> Upgrade to hof-build 1.6.0

apps/end-tenancy/acceptance/features/confirm.js, apps/end-tenancy/index.js, apps/end-tenancy/translations/src/en/buttons.json, apps/end-tenancy/views/confirm.html
https://jira.digital.homeoffice.gov.uk/browse/LCS-190
* Remove declaration
* remove related redundant acceptance tests
remove the acceptance checking that the user goes to confirmation step as this is changing as part of a declaration page being added in PR https://github.com/UKHomeOffice/end-tenancy/pull/84
=> [LCS-190] - Amend Confirm page

apps/end-tenancy/acceptance/features/confirm.js, apps/end-tenancy/behaviours/summary.js
The links in the change buttons were only being defined if the `step` that the field was from had a `field` property. Steps that use the Address Lookup behaviour and have no other fields do not have a `fields` property.
=> Ensure 'change' buttons link to the correct url.

assets/scss/app.scss
This is using the govuk elements form styles defined here: https://govuk-elements.herokuapp.com/form-elements/example-form-elements/
The selector will be reliable because postcode field configuration is driven from the address lookup behaviour, and so the name of the fields will always contain `postcode`. There are some old browsers that won't support the selector, but they will revert to a standard width field which is no big deal.
**before**
**after**
=> Reduces postcode width

assets/scss/app.scss
Previously, we were overriding the govuk h1 styling by making it smaller.  This was against the standards and not as accessible
=> Use default govuk h1 styling

apps/end-tenancy/acceptance/features/confirm.js, apps/end-tenancy/translations/src/en/fields.json
- Add prefix of landlord and agent to appropriate sections
To change the name of a label that appears on a field on the summary page, you need to provide a summary value so that takes precedence over the others, see here
https://github.com/UKHomeOffice/end-tenancy/blob/master/apps/end-tenancy/behaviours/summary.js#L49
=> [LCS-464] - Update summary & pdf labels

apps/end-tenancy/acceptance/features/use-previous.js, apps/end-tenancy/index.js
Bug: If a user selected use previous before the landlord address would not be saved. This has been fixed by adding the addressKey
=> [LCS-458] - Fix: store landlord address for use previous

apps/end-tenancy/translations/src/en/fields.json
=> [LCS-466] - Fix: Add triple braces to tenant-details

README.md
Jira ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-43
What: Redeploying end-tenancy to check it works on dev with the new version of file-vault. The file-vault version has been changed in the kube-end-tenency repo (https://github.com/UKHomeOffice/kube-end-tenancy/pull/77).
Why: To test the new version of file-vault is still compatible with the HOF services that use it.
=> SD-43: Update readme for redeployment to check new file-vault version

.drone.yml, .travis.yml, Dockerfile, package.json
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-723
**Changes**
- Updated image in drone pipeline build step to node:14
- Changed docker image from node:10.11-alpine to node:14-alpine.
- Updated package.json to include node version "14.16.1"
- Updated .travis.yml to use node-js 14
=> SD-725: Upgrade Node Version to 14

Dockerfile-acceptance, apps/end-tenancy/translations/src/en/cookies.json, apps/end-tenancy/views/content/cookies.md, apps/end-tenancy/views/cookies.html, package-lock.json
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-723
**Changes:**
- Cookie name changed from hof.sid to hod.sid in cookies.json and cookies.md to be inline with acceptance test default.
- Remove heading in cookies.md to correct double heading error. 
- Upgrade Node Version to 14 for acceptance tests (Dockerfile-acceptance file).
- Updated package-lock.json after Node 14 update.
=> SD 723 Update node version and Cookie name correction

package-lock.json, package.json
**Changes**	
- Updated hof-behaviour-emailer to version 2.2.1 to fix vulnerability in nodemailer via hof-emailer.
=> SD-779: Updated hof-behaviour emailer to fix vulnerability in nodemailer

package-lock.json, package.json
**What**
Upgraded hof-middlware to v2.2.4 
**Why**
Applications using this library could be vulnerable to a redirection exploit where an attacker can use a Home Office page to redirect someone to their malicious site
**How**
In hof-middleware ensure URLs are relative paths – i.e. they start with a single / character. Absolute URLs starting with // will be rejected.
**Test**
Unit test and url test (for example entering https://dev.notprod.ending-a-tenancy.homeoffice.gov.uk//bbc.co.uk should not redirect to bbc sit)
=> Upgraded hof-middlware to v2.2.4 to fix redirection to malicious sites

.drone.yml, apps/end-tenancy/models/upload-pdf.js, apps/end-tenancy/translations/src/en/fields.json, apps/end-tenancy/translations/src/en/pages.json, package.json, test/_unit/behaviours/upload-pdf.spec.js, yarn.lock
**Changes**
Stakeholders requested the PDF's become more uniformed in appearance across the 3 routes in end tenancy. 
Titles changed on the PDF's to reflect the type of application the users are making.
**Code changes**
- Upgraded HOF to 19.14.9
- Added translation for branch name URLs in test_acceptance_branch steps in drone.yaml file
- Added new title generator depending on route to upload-pdf.js
- Changed Name to Name of Tenant in fields.json
- pages.json updated with new PDF Headers for each route.
- upload-pdf.spec updated with unit tests for all PDF's and sorting logic tests
- moment updated to 2.29.3 in package.json
=> UKVIET-41: PDF Content Changes for all Routes

.drone.yml, server.js
Add the following CSP rules to service config
imgSrc: [
'www.google-analytics.com',
'ssl.gstatic.com',
'www.google.co.uk/ads/ga-audiences'
],
connectSrc: [
'https://www.google-analytics.com',
'https://region1.google-analytics.com',
'https://region1.analytics.google.com'
]
Support new GA analytics domain from https://region1.analytics.google.com to https://region1.google-analytics.com
=> UKVIET-40: add new CSP rules to service config

.drone.yml, .snyk, apps/end-tenancy/translations/src/en/accessibility.json, apps/end-tenancy/translations/src/en/pages.json, apps/end-tenancy/views/accessibility.html, pull-request-template.md, yarn.lock
- Update accessibility statement - [UKVIET-74](https://collaboration.homeoffice.gov.uk/jira/browse/UKVIET-74)
- UKVIET's accessibility statement is out of date and needs to cover WCAG 2.2 requirements and guidelines
- create accessibility.json file to overwrite default hof accessibility content where necessary
- move accessibility header from pages.json to accessibility for consistency in accessibility.html
- update accessibility.html with additional content and comments
- tests passing locally and on branch
- updated snyk ignore list
- updated yarn.lock
- removed anchore steps from drone.yml as they are to be replaced by trivy
=> UKVIET-74: Update accessibility statement

.drone.yml
- Update UAT acceptance test url in drone.yml - [UKVIET-75](https://collaboration.homeoffice.gov.uk/jira/browse/UKVIET-75)
- The uat url for UKVIET was changed but the url was not updated for the uat acceptance tests in drone.yml causing the uat acceptance tests to timeout in the drone build.
- Update UAT acceptance test host name in drone.yml
- can only be tested in merge build
=> UKVIET-75: Update UAT acceptance test url

.snyk, Dockerfile, Dockerfile-acceptance, apps/end-tenancy/models/upload.js, bin/deploy.sh, kube/file-vault/file-vault-deployment.yml, package.json, yarn.lock
- Update UKVIET  to use version of hof which replaces request module with axios  - [HOFF-689](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-689)
- The request module in hof is deprecated and has vulnerabilities so has been replaced by axios.
- update hof version in package.json
- update playwright to fix acceptance test
- update notifications-node-client to fix vulnerabilities
- update yarn.lock
- refactor models/upload to use axios
- tests passing locally, successful submission in branch
- updated snyk ignore list
- remove anchore step from drone as it is to be replaced by trivy
- update to node version 20
- remove 'UAT' from deploy_to_branch message to avoid confusion
=> HOFF-689: Update UKVI ending tenancy to version of hof using axios

kube/app/ingress-external.yml
[HOFF-1062](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1062) 
So we can whitelist with EBSA to access CTF
By adding and ext ingress
Deployment and adding manual IP to ensure we can access the ext url
=> HOFF-1062 - Adding ext ingress to service

kube/app/deployment.yml, kube/file-vault/file-vault-deployment.yml
- Updated the keycloak-proxy image for Keycloak v22 compatibility and vulnerability fixes.
- Updated the file-vault image to address security issues.
- We have already created (keycloak-user and keycloak-client) secrets in branch, uat and stage envs.
- This work covers [HOFF-963](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-963) and [HOFF-964](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-964)
- To ensure compatibility with Keycloak v22.
- To enhance security by fixing vulnerabilities in both keycloak-proxy and file-vault images.
- Lamp is using both these images.
- Upgraded the keycloak-proxy image to the latest version supporting Keycloak v22.
- Applied security patches to both images.
- Verified authentication flow and proxy protection.
- Ran security scans to …
=> HOFF-963: Use latest keycloak proxy image
