- apps/end-tenancy/acceptance/features/what.js
- apps/end-tenancy/acceptance/pages/check.js
- apps/end-tenancy/acceptance/pages/date-of-issue.js
- apps/end-tenancy/acceptance/pages/request.js
- apps/end-tenancy/acceptance/pages/what.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/journey.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/translations/src/en/validation.json
- apps/end-tenancy/views/partials/panel.html
- apps/end-tenancy/views/what.html
- apps/readme
- codecept.conf.js
- index.js
* added codecept scaffolding
* added journey scaffolding
* added first step
> LCS-94 - First Step

- apps/end-tenancy/acceptance/features/report-date.js
- apps/end-tenancy/acceptance/features/what.js
- apps/end-tenancy/acceptance/pages/property-address.js
- apps/end-tenancy/acceptance/pages/report-date.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/translations/src/en/validation.json
- apps/end-tenancy/views/report-nldp-date.html
- codecept.conf.js
- added step and acceptance tests
> LCS-95 report date step

- apps/end-tenancy/acceptance/features/property-address.js
- apps/end-tenancy/acceptance/pages/property-address.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/controllers/address-lookup.js
- apps/end-tenancy/index.js
- apps/end-tenancy/models/postcodes.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/address-lookup.html
- apps/end-tenancy/views/address.html
- codecept.conf.js
- config.js
- index.js
- mock-postcode.js
* added single controller to handle the address lookup - this will later be abstracted
* added acceptance tests
> LCS-96 - address lookup step(s)

- apps/end-tenancy/acceptance/features/property-address.js
- apps/end-tenancy/acceptance/pages/property-address.js
- apps/end-tenancy/translations/src/en/pages.json
Conditional translation added if user selected "check" journey
> Feature LCS-124 - changes to property address step

- apps/end-tenancy/acceptance/features/tenant-details.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/pages.json
Added conditional step in tenant loop - if check journey, skip date step.
Added conditional content - different label if checking tenant
> feature LCS-126 and LCS-125 - tenant loop

- apps/end-tenancy/acceptance/features/confirm.js
- apps/end-tenancy/acceptance/pages/confirm.js
- apps/end-tenancy/acceptance/pages/confirmation.js
- apps/end-tenancy/controllers/confirm.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/translations/src/en/validation.json
- apps/end-tenancy/views/confirm.html
- codecept.conf.js
* added summary translations for fields
* added missing validation translations
* extended confirm controller to display tenants lists
> Feature - LCS-117 - confirm step

- apps/end-tenancy/acceptance/features/confirmation.js
- apps/end-tenancy/acceptance/pages/confirmation.js
- apps/end-tenancy/controllers/confirmation.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/confirmation.html
* added confirmation page. Due to conditional translations, and sessionModel being cleared, this requires a custom controller
> Feature LCS-119 and LCS-127 - confirmation page

- apps/end-tenancy/controllers/confirm.js
- apps/end-tenancy/translations/src/en/pages.json
* included pkaceholder text for email intro, outro and subject
* added logic to extract the email address whether landlord or agent
> Feature - LCS-137 - format data for email

- apps/end-tenancy/acceptance/features/tenant-details.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/date.html
- apps/end-tenancy/views/partials/items-table.html
- apps/end-tenancy/views/tenant-details.html
- assets/scss/app.scss
* added partial to render table if one or more tenants added
* added link to change tenant details
* moved adding logic to post of penultimate step
> Feature - LCS-138 - loop summary table

- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/index.js
* if you click back after adding a tenant, and add another postcode, a tenant with a blank name is added
* added prereqs check - if these aren't complete, redirect to first subStep
> bugfix - LCS-141 - fix for tenant loop back link

- apps/end-tenancy/controllers/loop.js
* Due to changing the point at which the tenant is added, multiple tenants are no longer added on check journey
* abstracted forking logic
* use getNext to find out if next step is last
> bugfix - LCS-146 - add tenant loop broken on check journey

- apps/end-tenancy/translations/src/en/pages.json
This PR uses the new separate subject for customer/caseworker in so-master hof-controllers and hof-emailer#1.5.0
> Feature LCS-111 - added email content

- apps/end-tenancy/acceptance/features/agent-details.js
- apps/end-tenancy/acceptance/features/landlord-details.js
- apps/end-tenancy/acceptance/features/nldp-date.js
- apps/end-tenancy/acceptance/features/tenant-details.js
- apps/end-tenancy/acceptance/pages/landlord-name.js
- apps/end-tenancy/acceptance/pages/nldp-date.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/content.json
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/translations/src/en/validation.json
Amended contend as per notes in ticket LCS-112
> Amends - LCS-112 - content amends

- apps/end-tenancy/controllers/address-lookup.js
- apps/end-tenancy/controllers/confirm.js
- apps/end-tenancy/controllers/confirmation.js
- apps/end-tenancy/controllers/contact.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/index.js
- apps/end-tenancy/models/postcodes.js
- assets/js/index.js
- assets/scss/app.scss
- npm-shrinkwrap.json
- package.json
* use bootstrap#6
* added eslint-config-homeoffice
* added hof-frontend-toolkit
* fixed broken paths
* shrinkwrap the lot
> feature LCS-148 - no more so master

- assets/scss/app.scss
Included styles from ukvi complaints for confirmation message.
Todo: these need to be abstracted
> bugfix - LCS-151 - confirmation page padding

- apps/end-tenancy/acceptance/features/nldp-date.js
- apps/end-tenancy/acceptance/pages/nldp-date.js
- apps/end-tenancy/controllers/address-lookup.js
- apps/end-tenancy/translations/src/en/content.json
- apps/end-tenancy/translations/src/en/errorlist.json
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/what.html
* Updated content in line with content amend docuement
* Amended postcode lookup to display address if only one found§
> Amends - LCS-158 - content review

- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/translations/src/en/pages.json
Amended title for tenants summary
Fixed bug with showing intro text on first tenant only
> Amend - LCS-159 - content amends

- apps/end-tenancy/translations/src/en/pages.json
* removed intro paragraph from add-another step
> LCS-161 - Content amends

- Dockerfile
We don't want this hanging around on the docker image
> There should be no reason for git anymore

- apps/end-tenancy/acceptance/features/tenancy-start.js
- apps/end-tenancy/acceptance/pages/tenancy-start.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/validation.json
- apps/end-tenancy/views/tenancy-start.html
* added new tenancy start page for request route
* linked to from property address
* next step is tenant details
* added tests
> feature LCS-177 - tenancy start date

- apps/end-tenancy/acceptance/features/tenant-details.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
* added new conditional content for title of step if on request route
* added new placeholder for if more than one tenant added
* added new skeleton step - details
> feature LCS-178 and LCS-181 - tenants name request route

- apps/end-tenancy/acceptance/features/tenant-details.js
- apps/end-tenancy/acceptance/pages/tenant-details.js
- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/fields.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/translations/src/en/validation.json
- apps/end-tenancy/views/partials/date-of-birth.html
- apps/end-tenancy/views/partials/items-table.html
- assets/js/index.js
- npm-shrinkwrap.json
- package.json
* added fields to tenant details step
* added country typeahead
* updated loop to handle third case
* added acceptance tests
> Feature LCS-179 - tenant details, request journey

- apps/end-tenancy/translations/src/en/pages.json
* added conditional title and intro if requesting an nldp
> Feature - LCS-180 add another - request route

- apps/end-tenancy/translations/src/en/journey.json
- apps/end-tenancy/views/partials/navigation.html
Added a partial with a custom link to the service start page
> bugfix - LCS-173 - header link

- apps/end-tenancy/translations/src/en/pages.json
* updated from "What is the property address?" to "What is the address of the rental property?"
> LCS-176 - updated title in line with request

- apps/end-tenancy/controllers/confirm.js
- apps/end-tenancy/translations/src/en/pages.json
* fixed bug with field name used instead of substep when editing from the check answers page
* added conditional section title
> Feature - LCS-190 check answers request route

- apps/end-tenancy/controllers/loop.js
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/tenant-details.html
* added conditional translation to locals
* added translation for tenant details step
* added conditional `<p>` outro to template
> Amend LCS-179 - added outro text

- apps/end-tenancy/translations/src/en/fields.json
* removed brackets and changed wording for landlord company hint text as per service request
> LCS-197 text change

- .gitignore
- apps/end-tenancy/fields.js
- apps/end-tenancy/translations/src/en/validation.json
Fixes the bug below
https://jira.digital.homeoffice.gov.uk/browse/LCS-140
> Date of birth validation for when a date is too far in the past

- apps/end-tenancy/acceptance/features/confirmation.js
- apps/end-tenancy/acceptance/features/happy-path.js
- apps/end-tenancy/acceptance/features/landlord-address.js
- apps/end-tenancy/acceptance/pages/confirmation.js
- apps/end-tenancy/behaviours/get-declarer.js
- apps/end-tenancy/index.js
- apps/end-tenancy/translations/src/en/buttons.json
- apps/end-tenancy/translations/src/en/pages.json
- apps/end-tenancy/views/content/declaration.md
- apps/end-tenancy/views/declaration.html
- assets/scss/app.scss
- test/unit/behaviours/get-declarer.test.js
- Add happy path acceptance
- Move complete behaviour to declaration
- Fix a bug with bullet points
Note: I know there are a lot of commits but I think they add value
> [Lcs 292] - declaration

- apps/end-tenancy/acceptance/features/confirm-declaration.js
- apps/end-tenancy/acceptance/features/confirm.js
- apps/end-tenancy/acceptance/features/happy-path.js
- apps/end-tenancy/acceptance/pages/confirm-declaration.js
- apps/end-tenancy/acceptance/pages/confirm.js
- apps/end-tenancy/behaviours/email-caseworker.js
- apps/end-tenancy/behaviours/email-customer.js
- apps/end-tenancy/behaviours/email-pdf-caseworker.js
- apps/end-tenancy/behaviours/use-previous.js
- apps/end-tenancy/emails/customer.html
- apps/end-tenancy/emails/pdf-caseworker.html
- apps/end-tenancy/fields.js
- apps/end-tenancy/index.js
- apps/end-tenancy/views/confirm-declaration.html
- codecept.conf.js
- fork between confirm and confirm-declaration
- show declaration checkbox on /confirm
- email caseworker content from /confirm
> Make possible to email customers and caseworkers

- apps/end-tenancy/acceptance/features/confirm-declaration.js
- apps/end-tenancy/acceptance/pages/confirm-declaration.js
- apps/end-tenancy/behaviours/email-customer.js
- apps/end-tenancy/sections/confirm-page-sections.js
> [LCS-463] - remove nldp-date from customer email

- apps/end-tenancy/translations/src/en/pages.json
> [LCS-461] - Edit confirm-declaration header

- apps/end-tenancy/translations/src/en/email.json
Relates to mainly missing tenant information on the request nldp route
> [LCS-452] - Add missing email translations

- .drone.yml
I think this will push up a rebuilt image to quay of the old branch
> Rebuild old branch and push to quay

- apps/end-tenancy/behaviours/loop.js
* store array of completed subSteps
* backlink is previous completed subStep unless 1) it is the add-another page, in which case the backlink should be the previous main step, or 2) it is the first subStep
> Fixed bug with backlinks on loop pages

- apps/end-tenancy/emails/customer.html
- apps/end-tenancy/translations/src/en/content.json
- apps/end-tenancy/translations/src/en/pages.json
Linked Jira Ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-82
Changes:-
Changed telephone number to 0300 790 6268, in the response the landlord receives.
> Changed telephone number to 0300 790 6268

- .drone.yml
- apps/end-tenancy/acceptance/features/confirm.js
- apps/end-tenancy/acceptance/features/tenant-details.js
- package-lock.json
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-82
**Changes**	
* Added fixes for broken acceptance tests in features/tenant-details.js
* Changed URL for a broken acceptance test in confirm.js
* Amended drone.yml file to accept feature branches.
> SD-82: Fixing broken acceptance tests.

- index.js
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-233
**Changes:**
- Refactored index.js file.
- Removed terms-and-conditions.
- added module.exports to the end of the file.
> SD-233: Refactored index.js file and added module.exports

- .drone.yml
Change UAT link in drone pipeline
Previous link was not correct
> hard code UAT link in drone pipeline

- bin/deploy.sh
- kube/html-pdf/html-pdf-deployment.yml
- kube/redis/redis-deployment.yml
> updated annotations for downscaling for redis and html

- kube/app/deployment.yml
- kube/file-vault/file-vault-deployment.yml
- Update UKVIET UAT envs - [UKVIET-76](https://collaboration.homeoffice.gov.uk/jira/browse/UKVIET-76)
- Submissions on UKVIET UAT was failing with 503 error due to incorrect filevault urls
- update filevault urls in deployment.yml and filevault-deployment.yml
- update AWS s3 bucket secret names for branch and uat environments in filevault-deployment.yml
> UKVIET-76: update uat envs

- .drone.yml
- config.js
- package.json
- server.js
- yarn.lock
Update feedback URL by environment.  
- https://collaboration.homeoffice.gov.uk/jira/browse/UKVIET-79
- added ref to env feedback url (config.js)
- set value of feedback url to config value (server.js)
> UKVIET-79: Update Feedback Url

- .snyk
- apps/end-tenancy/translations/src/en/accessibility.json
- apps/end-tenancy/views/accessibility.html
Updated Accessibility Statement to remove Timeout. [UKVIET-89] (https://collaboration.homeoffice.gov.uk/jira/browse/UKVIET-89)
As per business requirement.
Removed some statements and updated some words in the accessibility.json and accessibility.html
Manual testing conducted to check the contents on accessibility page.
> UKVIET-89: Updated Accessibility Statement to remove Timeout.
